[2025-04-18T07:41:51.473+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-18T07:41:51.478+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: triphobo_tours_pipeline.load_tours_snowflake manual__2025-04-18T07:36:18.306091+00:00 [queued]>
[2025-04-18T07:41:51.481+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: triphobo_tours_pipeline.load_tours_snowflake manual__2025-04-18T07:36:18.306091+00:00 [queued]>
[2025-04-18T07:41:51.481+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-04-18T07:41:51.484+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): load_tours_snowflake> on 2025-04-18 07:36:18.306091+00:00
[2025-04-18T07:41:51.487+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=2179) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-04-18T07:41:51.488+0000] {standard_task_runner.py:72} INFO - Started process 2180 to run task
[2025-04-18T07:41:51.489+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'triphobo_tours_pipeline', 'load_tours_snowflake', 'manual__2025-04-18T07:36:18.306091+00:00', '--job-id', '74', '--raw', '--subdir', 'DAGS_FOLDER/itinerary_tours_dag.py', '--cfg-path', '/tmp/tmphmv56vgb']
[2025-04-18T07:41:51.490+0000] {standard_task_runner.py:105} INFO - Job 74: Subtask load_tours_snowflake
[2025-04-18T07:41:51.507+0000] {task_command.py:467} INFO - Running <TaskInstance: triphobo_tours_pipeline.load_tours_snowflake manual__2025-04-18T07:36:18.306091+00:00 [running]> on host 68d96c644388
[2025-04-18T07:41:51.530+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='triphobo_tours_pipeline' AIRFLOW_CTX_TASK_ID='load_tours_snowflake' AIRFLOW_CTX_EXECUTION_DATE='2025-04-18T07:36:18.306091+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-18T07:36:18.306091+00:00'
[2025-04-18T07:41:51.531+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-04-18T07:41:52.677+0000] {itinerary_tours_dag.py:477} INFO - Downloaded CSV with 1049 rows from s3://bigdatafinal2025/clean/tours_with_coords.csv
[2025-04-18T07:41:52.744+0000] {connection.py:414} INFO - Snowflake Connector for Python Version: 3.12.4, Python Version: 3.12.8, Platform: Linux-6.10.14-linuxkit-aarch64-with-glibc2.36
[2025-04-18T07:41:52.745+0000] {connection.py:1197} INFO - Connecting to GLOBAL Snowflake domain
[2025-04-18T07:41:52.745+0000] {connection.py:1278} INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
[2025-04-18T07:41:53.596+0000] {cursor.py:1166} INFO - Number of results in first chunk: 1
[2025-04-18T07:41:53.597+0000] {itinerary_tours_dag.py:527} INFO - Uploading file to Snowflake stage...
[2025-04-18T07:41:55.202+0000] {itinerary_tours_dag.py:546} INFO - Executing COPY INTO...
[2025-04-18T07:41:56.975+0000] {cursor.py:1166} INFO - Number of results in first chunk: 1
[2025-04-18T07:41:57.099+0000] {cursor.py:1166} INFO - Number of results in first chunk: 1
[2025-04-18T07:41:57.101+0000] {itinerary_tours_dag.py:551} INFO - Snowflake table row count: 1049
[2025-04-18T07:41:57.102+0000] {connection.py:789} INFO - closed
[2025-04-18T07:41:57.137+0000] {connection.py:795} INFO - No async queries seem to be running, deleting session
[2025-04-18T07:41:57.222+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-04-18T07:41:57.234+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-04-18T07:41:57.234+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=triphobo_tours_pipeline, task_id=load_tours_snowflake, run_id=manual__2025-04-18T07:36:18.306091+00:00, execution_date=20250418T073618, start_date=20250418T074151, end_date=20250418T074157
[2025-04-18T07:41:57.295+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-04-18T07:41:57.304+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-04-18T07:41:57.306+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
