[2025-04-18T01:42:05.036+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-18T01:42:05.045+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ihg_hotels_dag.scrape_hotels manual__2025-04-18T01:42:02.324528+00:00 [queued]>
[2025-04-18T01:42:05.050+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ihg_hotels_dag.scrape_hotels manual__2025-04-18T01:42:02.324528+00:00 [queued]>
[2025-04-18T01:42:05.050+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-04-18T01:42:05.055+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): scrape_hotels> on 2025-04-18 01:42:02.324528+00:00
[2025-04-18T01:42:05.059+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=221) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-04-18T01:42:05.061+0000] {standard_task_runner.py:72} INFO - Started process 230 to run task
[2025-04-18T01:42:05.060+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'ihg_hotels_dag', 'scrape_hotels', 'manual__2025-04-18T01:42:02.324528+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/hotel_scrape_dag.py', '--cfg-path', '/tmp/tmpp0tf5ric']
[2025-04-18T01:42:05.062+0000] {standard_task_runner.py:105} INFO - Job 3: Subtask scrape_hotels
[2025-04-18T01:42:05.095+0000] {task_command.py:467} INFO - Running <TaskInstance: ihg_hotels_dag.scrape_hotels manual__2025-04-18T01:42:02.324528+00:00 [running]> on host a8651540ef5d
[2025-04-18T01:42:05.146+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='ihg_hotels_dag' AIRFLOW_CTX_TASK_ID='scrape_hotels' AIRFLOW_CTX_EXECUTION_DATE='2025-04-18T01:42:02.324528+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-18T01:42:02.324528+00:00'
[2025-04-18T01:42:05.148+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-04-18T01:42:05.180+0000] {hotel_scrape_dag.py:81} INFO - Starting hotel scraping process
[2025-04-18T01:42:05.181+0000] {hotel_scrape_dag.py:85} INFO - Attempting to scrape using known hotel URLs
[2025-04-18T01:42:05.182+0000] {hotel_scrape_dag.py:155} INFO - Scraping known hotels for New York
[2025-04-18T01:42:05.182+0000] {hotel_scrape_dag.py:166} INFO - Scraping Holiday Inn Manhattan-Financial District at https://www.ihg.com/holidayinn/hotels/us/en/nycmk/hoteldetail
[2025-04-18T01:42:05.273+0000] {hotel_scrape_dag.py:169} INFO - Request returned status: 403
[2025-04-18T01:42:06.933+0000] {hotel_scrape_dag.py:166} INFO - Scraping Holiday Inn New York City - Times Square at https://www.ihg.com/holidayinn/hotels/us/en/nycre/hoteldetail
[2025-04-18T01:42:07.034+0000] {hotel_scrape_dag.py:169} INFO - Request returned status: 403
[2025-04-18T01:42:08.599+0000] {hotel_scrape_dag.py:166} INFO - Scraping InterContinental New York Times Square at https://www.ihg.com/intercontinental/hotels/us/en/nycic/hoteldetail
[2025-04-18T01:42:08.714+0000] {hotel_scrape_dag.py:169} INFO - Request returned status: 403
[2025-04-18T01:42:10.478+0000] {hotel_scrape_dag.py:166} INFO - Scraping Kimpton Hotel Eventi at https://www.ihg.com/kimpton/hotels/us/en/nycxn/hoteldetail
[2025-04-18T01:42:10.549+0000] {hotel_scrape_dag.py:169} INFO - Request returned status: 403
[2025-04-18T01:42:11.734+0000] {hotel_scrape_dag.py:240} INFO - Added 0 hotels for New York
[2025-04-18T01:42:11.734+0000] {hotel_scrape_dag.py:155} INFO - Scraping known hotels for San Francisco
[2025-04-18T01:42:11.734+0000] {hotel_scrape_dag.py:166} INFO - Scraping Holiday Inn San Francisco-Golden Gateway at https://www.ihg.com/holidayinn/hotels/us/en/sfogg/hoteldetail
[2025-04-18T01:42:11.867+0000] {hotel_scrape_dag.py:169} INFO - Request returned status: 403
[2025-04-18T01:42:13.552+0000] {hotel_scrape_dag.py:166} INFO - Scraping Holiday Inn Express San Francisco Union Square at https://www.ihg.com/holidayinn/hotels/us/en/sfofn/hoteldetail
[2025-04-18T01:42:13.639+0000] {hotel_scrape_dag.py:169} INFO - Request returned status: 403
[2025-04-18T01:42:15.062+0000] {hotel_scrape_dag.py:166} INFO - Scraping InterContinental San Francisco at https://www.ihg.com/intercontinental/hotels/us/en/sfofs/hoteldetail
[2025-04-18T01:42:15.152+0000] {hotel_scrape_dag.py:169} INFO - Request returned status: 403
[2025-04-18T01:42:16.999+0000] {hotel_scrape_dag.py:240} INFO - Added 0 hotels for San Francisco
[2025-04-18T01:42:17.001+0000] {hotel_scrape_dag.py:155} INFO - Scraping known hotels for Chicago
[2025-04-18T01:42:17.001+0000] {hotel_scrape_dag.py:166} INFO - Scraping Holiday Inn Chicago Downtown at https://www.ihg.com/holidayinn/hotels/us/en/chidw/hoteldetail
[2025-04-18T01:42:17.079+0000] {hotel_scrape_dag.py:169} INFO - Request returned status: 403
[2025-04-18T01:42:18.791+0000] {hotel_scrape_dag.py:166} INFO - Scraping Holiday Inn Chicago-Mart Plaza River North at https://www.ihg.com/holidayinn/hotels/us/en/chird/hoteldetail
[2025-04-18T01:42:18.866+0000] {hotel_scrape_dag.py:169} INFO - Request returned status: 403
[2025-04-18T01:42:20.583+0000] {hotel_scrape_dag.py:166} INFO - Scraping InterContinental Chicago Magnificent Mile at https://www.ihg.com/intercontinental/hotels/us/en/chimg/hoteldetail
[2025-04-18T01:42:20.666+0000] {hotel_scrape_dag.py:169} INFO - Request returned status: 403
[2025-04-18T01:42:21.895+0000] {hotel_scrape_dag.py:240} INFO - Added 0 hotels for Chicago
[2025-04-18T01:42:21.897+0000] {hotel_scrape_dag.py:155} INFO - Scraping known hotels for Seattle
[2025-04-18T01:42:21.897+0000] {hotel_scrape_dag.py:166} INFO - Scraping Holiday Inn Seattle Downtown at https://www.ihg.com/holidayinn/hotels/us/en/seasc/hoteldetail
[2025-04-18T01:42:21.971+0000] {hotel_scrape_dag.py:169} INFO - Request returned status: 403
[2025-04-18T01:42:23.831+0000] {hotel_scrape_dag.py:166} INFO - Scraping Crowne Plaza Seattle-Downtown at https://www.ihg.com/crowneplaza/hotels/us/en/seatc/hoteldetail
[2025-04-18T01:42:23.924+0000] {hotel_scrape_dag.py:169} INFO - Request returned status: 403
[2025-04-18T01:42:25.421+0000] {hotel_scrape_dag.py:240} INFO - Added 0 hotels for Seattle
[2025-04-18T01:42:25.421+0000] {hotel_scrape_dag.py:155} INFO - Scraping known hotels for Las Vegas
[2025-04-18T01:42:25.421+0000] {hotel_scrape_dag.py:166} INFO - Scraping Holiday Inn Club Vacations At Desert Club Resort at https://www.ihg.com/holidayinnclub/hotels/us/en/lasvs/hoteldetail
[2025-04-18T01:42:25.490+0000] {hotel_scrape_dag.py:169} INFO - Request returned status: 403
[2025-04-18T01:42:26.674+0000] {hotel_scrape_dag.py:166} INFO - Scraping Holiday Inn Express Las Vegas South at https://www.ihg.com/holidayinn/hotels/us/en/lashn/hoteldetail
[2025-04-18T01:42:26.771+0000] {hotel_scrape_dag.py:169} INFO - Request returned status: 403
[2025-04-18T01:42:28.456+0000] {hotel_scrape_dag.py:240} INFO - Added 0 hotels for Las Vegas
[2025-04-18T01:42:28.457+0000] {hotel_scrape_dag.py:155} INFO - Scraping known hotels for Los Angeles
[2025-04-18T01:42:28.458+0000] {hotel_scrape_dag.py:166} INFO - Scraping Holiday Inn Los Angeles - LAX Airport at https://www.ihg.com/holidayinn/hotels/us/en/laxap/hoteldetail
[2025-04-18T01:42:28.534+0000] {hotel_scrape_dag.py:169} INFO - Request returned status: 403
[2025-04-18T01:42:30.325+0000] {local_task_job_runner.py:346} WARNING - State of this instance has been externally set to None. Terminating instance.
[2025-04-18T01:42:30.327+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-04-18T01:42:30.328+0000] {process_utils.py:132} INFO - Sending 15 to group 230. PIDs of all processes in the group: [230]
[2025-04-18T01:42:30.328+0000] {process_utils.py:87} INFO - Sending the signal 15 to group 230
[2025-04-18T01:42:30.328+0000] {taskinstance.py:3093} ERROR - Received SIGTERM. Terminating subprocesses.
[2025-04-18T01:42:30.333+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/hotel_scrape_dag.py", line 476, in run_scraping
    return scrape_hotels()
           ^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/hotel_scrape_dag.py", line 86, in scrape_hotels
    known_hotels = scrape_known_hotels()
                   ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/hotel_scrape_dag.py", line 234, in scrape_known_hotels
    time.sleep(random.uniform(1, 2))
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3095, in signal_handler
    raise AirflowTaskTerminated("Task received SIGTERM signal")
airflow.exceptions.AirflowTaskTerminated: Task received SIGTERM signal
[2025-04-18T01:42:30.336+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=ihg_hotels_dag, task_id=scrape_hotels, run_id=manual__2025-04-18T01:42:02.324528+00:00, execution_date=20250418T014202, start_date=20250418T014205, end_date=20250418T014230
[2025-04-18T01:42:30.341+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-04-18T01:42:30.341+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 3 for task scrape_hotels ((psycopg2.errors.ForeignKeyViolation) insert or update on table "task_fail" violates foreign key constraint "task_fail_ti_fkey"
DETAIL:  Key (dag_id, task_id, run_id, map_index)=(ihg_hotels_dag, scrape_hotels, manual__2025-04-18T01:42:02.324528+00:00, -1) is not present in table "task_instance".

[SQL: INSERT INTO task_fail (task_id, dag_id, run_id, map_index, start_date, end_date, duration) VALUES (%(task_id)s, %(dag_id)s, %(run_id)s, %(map_index)s, %(start_date)s, %(end_date)s, %(duration)s) RETURNING task_fail.id]
[parameters: {'task_id': 'scrape_hotels', 'dag_id': 'ihg_hotels_dag', 'run_id': 'manual__2025-04-18T01:42:02.324528+00:00', 'map_index': -1, 'start_date': datetime.datetime(2025, 4, 18, 1, 42, 5, 46185, tzinfo=Timezone('UTC')), 'end_date': datetime.datetime(2025, 4, 18, 1, 42, 30, 336083, tzinfo=Timezone('UTC')), 'duration': 25}]
(Background on this error at: https://sqlalche.me/e/14/gkpj); 230)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/hotel_scrape_dag.py", line 476, in run_scraping
    return scrape_hotels()
           ^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/hotel_scrape_dag.py", line 86, in scrape_hotels
    known_hotels = scrape_known_hotels()
                   ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/hotel_scrape_dag.py", line 234, in scrape_known_hotels
    time.sleep(random.uniform(1, 2))
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3095, in signal_handler
    raise AirflowTaskTerminated("Task received SIGTERM signal")
airflow.exceptions.AirflowTaskTerminated: Task received SIGTERM signal

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1910, in _execute_context
    self.dialect.do_execute(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/default.py", line 736, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.ForeignKeyViolation: insert or update on table "task_fail" violates foreign key constraint "task_fail_ti_fkey"
DETAIL:  Key (dag_id, task_id, run_id, map_index)=(ihg_hotels_dag, scrape_hotels, manual__2025-04-18T01:42:02.324528+00:00, -1) is not present in table "task_instance".


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 327, in _run_raw_task
    ti.handle_failure(e, test_mode, context, session=session)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 94, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3428, in handle_failure
    _handle_failure(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 94, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/api_internal/internal_api_call.py", line 166, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 1243, in _handle_failure
    TaskInstance.save_to_db(failure_context["ti"], session)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/api_internal/internal_api_call.py", line 166, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 94, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3400, in save_to_db
    session.flush()
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 3449, in flush
    self._flush(objects)
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 3588, in _flush
    with util.safe_reraise():
         ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 3549, in _flush
    flush_context.execute()
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/orm/unitofwork.py", line 456, in execute
    rec.execute(self)
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/orm/unitofwork.py", line 630, in execute
    util.preloaded.orm_persistence.save_obj(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/orm/persistence.py", line 245, in save_obj
    _emit_insert_statements(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/orm/persistence.py", line 1238, in _emit_insert_statements
    result = connection._execute_20(
             ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1710, in _execute_20
    return meth(self, args_10style, kwargs_10style, execution_options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/sql/elements.py", line 334, in _execute_on_connection
    return connection._execute_clauseelement(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1577, in _execute_clauseelement
    ret = self._execute_context(
          ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1953, in _execute_context
    self._handle_dbapi_exception(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 2134, in _handle_dbapi_exception
    util.raise_(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1910, in _execute_context
    self.dialect.do_execute(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/default.py", line 736, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.IntegrityError: (psycopg2.errors.ForeignKeyViolation) insert or update on table "task_fail" violates foreign key constraint "task_fail_ti_fkey"
DETAIL:  Key (dag_id, task_id, run_id, map_index)=(ihg_hotels_dag, scrape_hotels, manual__2025-04-18T01:42:02.324528+00:00, -1) is not present in table "task_instance".

[SQL: INSERT INTO task_fail (task_id, dag_id, run_id, map_index, start_date, end_date, duration) VALUES (%(task_id)s, %(dag_id)s, %(run_id)s, %(map_index)s, %(start_date)s, %(end_date)s, %(duration)s) RETURNING task_fail.id]
[parameters: {'task_id': 'scrape_hotels', 'dag_id': 'ihg_hotels_dag', 'run_id': 'manual__2025-04-18T01:42:02.324528+00:00', 'map_index': -1, 'start_date': datetime.datetime(2025, 4, 18, 1, 42, 5, 46185, tzinfo=Timezone('UTC')), 'end_date': datetime.datetime(2025, 4, 18, 1, 42, 30, 336083, tzinfo=Timezone('UTC')), 'duration': 25}]
(Background on this error at: https://sqlalche.me/e/14/gkpj)
[2025-04-18T01:42:30.360+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=230, status='terminated', exitcode=1, started='01:42:04') (230) terminated with exit code 1
