[2025-04-18T00:25:24.647+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-18T00:25:24.651+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: triphobo_attractions_pipeline.load_geocoded_attractions_snowflake manual__2025-04-18T00:25:23.654802+00:00 [queued]>
[2025-04-18T00:25:24.654+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: triphobo_attractions_pipeline.load_geocoded_attractions_snowflake manual__2025-04-18T00:25:23.654802+00:00 [queued]>
[2025-04-18T00:25:24.654+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-04-18T00:25:24.658+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): load_geocoded_attractions_snowflake> on 2025-04-18 00:25:23.654802+00:00
[2025-04-18T00:25:24.660+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=233) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-04-18T00:25:24.661+0000] {standard_task_runner.py:72} INFO - Started process 234 to run task
[2025-04-18T00:25:24.661+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'triphobo_attractions_pipeline', 'load_geocoded_attractions_snowflake', 'manual__2025-04-18T00:25:23.654802+00:00', '--job-id', '438', '--raw', '--subdir', 'DAGS_FOLDER/attractions_dag.py', '--cfg-path', '/tmp/tmp77cdli8d']
[2025-04-18T00:25:24.662+0000] {standard_task_runner.py:105} INFO - Job 438: Subtask load_geocoded_attractions_snowflake
[2025-04-18T00:25:24.677+0000] {task_command.py:467} INFO - Running <TaskInstance: triphobo_attractions_pipeline.load_geocoded_attractions_snowflake manual__2025-04-18T00:25:23.654802+00:00 [running]> on host 56616e1d0c73
[2025-04-18T00:25:24.703+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='triphobo_attractions_pipeline' AIRFLOW_CTX_TASK_ID='load_geocoded_attractions_snowflake' AIRFLOW_CTX_EXECUTION_DATE='2025-04-18T00:25:23.654802+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-18T00:25:23.654802+00:00'
[2025-04-18T00:25:24.703+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-04-18T00:25:24.761+0000] {attractions_dag.py:67} INFO - Downloading file from s3://bigdatafinal2025/clean/attractions_with_coords.csv
[2025-04-18T00:25:25.742+0000] {attractions_dag.py:71} INFO - CSV contains 855 rows and 14 columns
[2025-04-18T00:25:25.773+0000] {connection.py:414} INFO - Snowflake Connector for Python Version: 3.12.4, Python Version: 3.12.8, Platform: Linux-6.10.14-linuxkit-aarch64-with-glibc2.36
[2025-04-18T00:25:25.773+0000] {connection.py:1197} INFO - Connecting to GLOBAL Snowflake domain
[2025-04-18T00:25:25.774+0000] {connection.py:1278} INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
[2025-04-18T00:25:26.525+0000] {attractions_dag.py:82} INFO - Recreating table TRIPHOBO_ATTRACTIONS...
[2025-04-18T00:25:26.690+0000] {cursor.py:1166} INFO - Number of results in first chunk: 1
[2025-04-18T00:25:26.933+0000] {cursor.py:1166} INFO - Number of results in first chunk: 1
[2025-04-18T00:25:26.934+0000] {attractions_dag.py:93} INFO - Uploading file to Snowflake stage...
[2025-04-18T00:25:27.883+0000] {attractions_dag.py:112} INFO - Copying data into Snowflake table...
[2025-04-18T00:25:29.230+0000] {cursor.py:1166} INFO - Number of results in first chunk: 1
[2025-04-18T00:25:29.398+0000] {cursor.py:1166} INFO - Number of results in first chunk: 1
[2025-04-18T00:25:29.400+0000] {attractions_dag.py:117} INFO - Snowflake table row count: 855
[2025-04-18T00:25:29.401+0000] {connection.py:789} INFO - closed
[2025-04-18T00:25:29.441+0000] {connection.py:795} INFO - No async queries seem to be running, deleting session
[2025-04-18T00:25:29.509+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-04-18T00:25:29.518+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-04-18T00:25:29.518+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=triphobo_attractions_pipeline, task_id=load_geocoded_attractions_snowflake, run_id=manual__2025-04-18T00:25:23.654802+00:00, execution_date=20250418T002523, start_date=20250418T002524, end_date=20250418T002529
[2025-04-18T00:25:29.561+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-04-18T00:25:29.570+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-04-18T00:25:29.570+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
