[2025-04-18T07:20:05.739+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-18T07:20:05.744+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: triphobo_tours_pipeline.geocode_tours manual__2025-04-18T05:59:40.352376+00:00 [queued]>
[2025-04-18T07:20:05.747+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: triphobo_tours_pipeline.geocode_tours manual__2025-04-18T05:59:40.352376+00:00 [queued]>
[2025-04-18T07:20:05.747+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-04-18T07:20:05.751+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): geocode_tours> on 2025-04-18 05:59:40.352376+00:00
[2025-04-18T07:20:05.754+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=1797) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-04-18T07:20:05.755+0000] {standard_task_runner.py:72} INFO - Started process 1798 to run task
[2025-04-18T07:20:05.756+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'triphobo_tours_pipeline', 'geocode_tours', 'manual__2025-04-18T05:59:40.352376+00:00', '--job-id', '64', '--raw', '--subdir', 'DAGS_FOLDER/itinerary_tours_dag.py', '--cfg-path', '/tmp/tmpdxvmnf62']
[2025-04-18T07:20:05.757+0000] {standard_task_runner.py:105} INFO - Job 64: Subtask geocode_tours
[2025-04-18T07:20:05.773+0000] {task_command.py:467} INFO - Running <TaskInstance: triphobo_tours_pipeline.geocode_tours manual__2025-04-18T05:59:40.352376+00:00 [running]> on host 68d96c644388
[2025-04-18T07:20:05.799+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='triphobo_tours_pipeline' AIRFLOW_CTX_TASK_ID='geocode_tours' AIRFLOW_CTX_EXECUTION_DATE='2025-04-18T05:59:40.352376+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-18T05:59:40.352376+00:00'
[2025-04-18T07:20:05.800+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-04-18T07:20:05.805+0000] {itinerary_tours_dag.py:397} INFO - Processing file from /tmp/triphobo_data/cleaned_tours.csv to /tmp/triphobo_data/tours_with_coords.csv
[2025-04-18T07:20:05.805+0000] {itinerary_tours_dag.py:392} ERROR - Error processing CSV: name 'csv' is not defined
Traceback (most recent call last):
  File "/opt/airflow/dags/itinerary_tours_dag.py", line 335, in process_csv_in_batches
    reader = csv.DictReader(input_file)
             ^^^
NameError: name 'csv' is not defined. Did you forget to import 'csv'
[2025-04-18T07:20:05.806+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/itinerary_tours_dag.py", line 398, in add_coordinates_to_csv
    process_csv_in_batches(input_path, output_path, batch_size=50)
  File "/opt/airflow/dags/itinerary_tours_dag.py", line 335, in process_csv_in_batches
    reader = csv.DictReader(input_file)
             ^^^
NameError: name 'csv' is not defined. Did you forget to import 'csv'
[2025-04-18T07:20:05.812+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=triphobo_tours_pipeline, task_id=geocode_tours, run_id=manual__2025-04-18T05:59:40.352376+00:00, execution_date=20250418T055940, start_date=20250418T072005, end_date=20250418T072005
[2025-04-18T07:20:05.815+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-04-18T07:20:05.815+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 64 for task geocode_tours (name 'csv' is not defined; 1798)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/itinerary_tours_dag.py", line 398, in add_coordinates_to_csv
    process_csv_in_batches(input_path, output_path, batch_size=50)
  File "/opt/airflow/dags/itinerary_tours_dag.py", line 335, in process_csv_in_batches
    reader = csv.DictReader(input_file)
             ^^^
NameError: name 'csv' is not defined. Did you forget to import 'csv'
[2025-04-18T07:20:05.856+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-04-18T07:20:05.864+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-04-18T07:20:05.865+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
