[2025-04-17T21:20:49.309+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-17T21:20:49.315+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: triphobo_tours_pipeline.upload_raw_tours scheduled__2025-04-16T07:30:00+00:00 [queued]>
[2025-04-17T21:20:49.317+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: triphobo_tours_pipeline.upload_raw_tours scheduled__2025-04-16T07:30:00+00:00 [queued]>
[2025-04-17T21:20:49.317+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-04-17T21:20:49.321+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): upload_raw_tours> on 2025-04-16 07:30:00+00:00
[2025-04-17T21:20:49.325+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=1307) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-04-17T21:20:49.326+0000] {standard_task_runner.py:72} INFO - Started process 1308 to run task
[2025-04-17T21:20:49.326+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'triphobo_tours_pipeline', 'upload_raw_tours', 'scheduled__2025-04-16T07:30:00+00:00', '--job-id', '400', '--raw', '--subdir', 'DAGS_FOLDER/itinerary_tours_dag.py', '--cfg-path', '/tmp/tmp6768_eig']
[2025-04-17T21:20:49.328+0000] {standard_task_runner.py:105} INFO - Job 400: Subtask upload_raw_tours
[2025-04-17T21:20:49.349+0000] {task_command.py:467} INFO - Running <TaskInstance: triphobo_tours_pipeline.upload_raw_tours scheduled__2025-04-16T07:30:00+00:00 [running]> on host 4d0efc92e922
[2025-04-17T21:20:49.378+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='triphobo_tours_pipeline' AIRFLOW_CTX_TASK_ID='upload_raw_tours' AIRFLOW_CTX_EXECUTION_DATE='2025-04-16T07:30:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-04-16T07:30:00+00:00'
[2025-04-17T21:20:49.379+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-04-17T21:20:51.532+0000] {upload_to_S3.py:33} ERROR - Failed to upload /tmp/triphobo_data/triphobo_multi_city_tours.csv to s3://None/raw/triphobo_multi_city_tours.csv: expected string or bytes-like object, got 'NoneType'
[2025-04-17T21:20:51.533+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-04-17T21:20:51.537+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-04-17T21:20:51.537+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=triphobo_tours_pipeline, task_id=upload_raw_tours, run_id=scheduled__2025-04-16T07:30:00+00:00, execution_date=20250416T073000, start_date=20250417T212049, end_date=20250417T212051
[2025-04-17T21:20:51.561+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-04-17T21:20:51.571+0000] {taskinstance.py:3895} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-04-17T21:20:51.571+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
